insert into publisherContact values(sequence_id.nextval, '9A & 12', 'New Delhi', 'Hauz khas Village', 7123129378);
insert into publisherContact values(sequence_id.nextval, '2nd Floor, Munshilal Building', 'New Delhi', 'Connaught Palace', 7123163378);
insert into publisherContact values(sequence_id.nextval, '45th A 2nd Cross', 'New Delhi', 'Golf Course Road', 7123129319);
insert into publisherContact values(sequence_id.nextval, '31B 46th Cross', 'New Delhi', 'Greater Kailash', 9123129378);
insert into publisherContact values(sequence_id.nextval, 'Ground Floor', 'New Delhi', 'Chanakyapuri', 7123191778);
insert into publisherContact values(sequence_id.nextval, '43A/12-21', 'New Delhi', 'DLF Phase 4', 7191191778);
insert into publisherContact values(sequence_id.nextval, '91-12-21A', 'New Delhi', 'Bhikaji Cama Place', 7123192678);
insert into publisherContact values(sequence_id.nextval, '917/21-17, Second Floor', 'New Delhi', 'Defense Colony', 7123191778);
insert into publisherContact values(sequence_id.nextval, '43/19A, Second House', 'New Delhi', 'Sundar Nagar', 7018391778);
insert into publisherContact values(sequence_id.nextval, '9/1/2/4/1, Second Street', 'New Delhi', 'Lodhi Road', 7123191778);

insert into publisher values(sequence_id.nextval, 'Arihant Publications', 1);
insert into publisher values(sequence_id.nextval, 'S. Chand Publications', 2);
insert into publisher values(sequence_id.nextval, 'Pearson', 3);
insert into publisher values(sequence_id.nextval, 'McGraw-Hill Education', 4);
insert into publisher values(sequence_id.nextval, 'Wiley', 5);
insert into publisher values(sequence_id.nextval, 'Khanna Publications',6);
insert into publisher values(sequence_id.nextval, 'Shroff O Reilly',7);
insert into publisher values(sequence_id.nextval, 'Scholastic',8);
insert into publisher values(sequence_id.nextval, 'BPB Publications',9);
insert into publisher values(sequence_id.nextval, 'Dover Publications',10);

insert into authorContact values(sequence_id.nextval, 'wren@gmail.com', 9798654377, 'NH-3', 'Rajendra Nagar','New Delhi');
insert into authorContact values(sequence_id.nextval, 'ykanetkar@gmail.com', 9796754377, 'Sector 14', 'Circular Road','Kanpur');
insert into authorContact values(sequence_id.nextval, 'kreyszig@gmail.com', 8798654377, 'Sona Path', 'Dak Bungalow','Patna');
insert into authorContact values(sequence_id.nextval, 'grewal@gmail.com', 8898654377, 'Boring Road', 'Income Tax','Patna');
insert into authorContact values(sequence_id.nextval, 'pnag@gmail.com', 9098654377, 'Old Palace', 'Vaishalli','New Delhi');
insert into authorContact values(sequence_id.nextval, 'dcpandey@gmail.com', 9099714377, 'New Palace', 'Iffco Chowk','Chennai');
insert into authorContact values(sequence_id.nextval, 'ericgamma@gmail.com', 9018314377, 'Old Palace', 'Sector 32','Madurai');
insert into authorContact values(sequence_id.nextval, 'richardhelm@gmail.com', 9018311847, 'Old Fort', 'Ardee City','Bombay');
insert into authorContact values(sequence_id.nextval, 'ralphjohnson@gmail.com', 7198311847, 'Near Bus Stop', 'Marthahalli','Bangalore');
insert into authorContact values(sequence_id.nextval, 'johnvissidies@gmail.com', 9018319147, 'Beside Pvr Mall', 'Ardee City','Jaipur');
insert into authorContact values(sequence_id.nextval, 'ericfreeman@gmail.com', 8192319147, 'Beside Sector 49 Mall', 'Sector 49','Noida');
insert into authorContact values(sequence_id.nextval, 'thomascormen@gmail.com', 8192149147, 'Opp. Unitech Infospace', 'Old Delhi Gurgaon Road','Gurgaon');
insert into authorContact values(sequence_id.nextval, 'ronaldrivest@gmail.com', 8927149147, 'Cyber Hub', 'DLF Cyber City','Gurgaon');
insert into authorContact values(sequence_id.nextval, 'kathysierra@gmail.com', 8927999147, 'Opp. MGF Mall', 'MG Road','Gurgaon');
insert into authorContact values(sequence_id.nextval, 'bertbates@gmail.com', 8927999147, 'Sohna Road', 'Sector 57','Gurgaon');
insert into author_contact values(sequence_id.nextval, 'bsMainee@gmail.com', 8008654377, 'Link Road', 'Exibition Road','Lucknow');
insert into author_contact values(sequence_id.nextval, 'akjain@gmail.com', 8012354377, 'Lajpat Nagar', 'Near City Palace','New Delhi');
insert into author_contact values(sequence_id.nextval, 'bmgandhi@gmail.com', 9094290377, 'Mayur Vihar', 'Block A','Varanasi');
insert into author_contact values(sequence_id.nextval, 'PrakashKumar@gmail.com', 7798654377, 'Uttkal University', 'Vani Vihar','Bhubneshwar');
insert into author_contact values(sequence_id.nextval, 'Vkpuri@gmail.com', 8011654377, 'Dasuya', 'City Palace','Lucknow');


insert into author values(sequence_id.nextval, 'Wren Martin',1);
insert into author values(sequence_id.nextval, 'Yashwant Kanetkar', 2);
insert into author values(sequence_id.nextval, 'Ralph Johnson', 9);
insert into author values(sequence_id.nextval, 'William Kreyszig', 3);
insert into author values(sequence_id.nextval, 'B.S.Grewal', 4);
insert into author values(sequence_id.nextval, 'John Vlssidies', 10);
insert into author values(sequence_id.nextval, 'P.Nag', 5);
insert into author values(sequence_id.nextval, 'D.C.Pandey', 6);
insert into author values(sequence_id.nextval, 'Ronald R.Rivest', 13);
insert into author values(sequence_id.nextval, 'Eric Gamma', 7);
insert into author values(sequence_id.nextval, 'Richard Helm', 8);
insert into author values(sequence_id.nextval, 'Eric Freeman', 11);
insert into author values(sequence_id.nextval, 'Thomas H.Cormen', 12);
insert into author values(sequence_id.nextval, 'Kathy Sierra', 14);
insert into author values(sequence_id.nextval, 'Bert Bates', 15);
insert into author values(sequence_id.nextval, 'B.S Mainee', 16);
insert into author values(sequence_id.nextval, 'A.K Jain', 17);
insert into author values(sequence_id.nextval, 'B.M Gandhi', 18);
insert into author values(sequence_id.nextval, 'Prakash Kumar', 19);
insert into author values(sequence_id.nextval, 'V.K Puri', 20);


insert into storeContact values(1,9876543215,'Link Road','Old Palace','New Delhi');
insert into storeContact values(2,9876548819,'Sector 22','Dairy Lane','gurgaon');
insert into storeContact values(3,9876544705,'Patliputra colony','P n M Mall','Patna');
insert into storeContact values(4,9876543267,'S.G.Park','NH-17','Agra');
insert into storeContact values(5,9876546580,'Huda Market','M.G Road','Gurgaon');
insert into store_contact values(6,8001546580,'N P Center','Lajpat Nagar','Varanasi');
insert into store_contact values(7,7001546580,'Church Gate','Aashiana Road','Banglore');
insert into store_contact values(8,8090546580,'Circular Road','Rajendra Nagar','Vishakhapatnam');
insert into store_contact values(9,8090546580,'Service Center','Industrial Area','Gurgaon');
insert into store_contact values(10,7716546580,'SuperMart-1 Phase-4','NH3','Dwarka');

insert into store values(1,'Books Plaza',1);
insert into store values(2,'Gyan Ganga',2);
insert into store values(3,'Book Store',3);
insert into store values(4,'Books n Anmee',4);
insert into store values(5,'Pustakam',5);
insert into store values(6,'Books For All',6);
insert into store values(7,'Books Center',7);
insert into store values(8,'Books Stop',8);
insert into store values(9,'Readers Heaven',9);
insert into store values(10,'Book Mart',10);

insert into book values(1, 'Understanding Physics for Jee', 202, 1,'1.jpg');
insert into book values(2, 'Design Patterns - Elements of Reusable Object Oriented Software', 523,3,'2.jpg');
insert into book values(3, 'High School English Grammar and Composition', 385,2,'3.jpg');
insert into book values(4, 'Introduction to Algorithms', 876,3,'4.jpg');
insert into book values(5, 'Product Design & Development(SIE)', 202, 4,'5.jpg');
insert into book values(6, 'A Final Course in Grammar and Composition', 150,2,'6.jpg');
insert into book values(7, 'What to eat if you have Diabetes - Healing Foods', 1329, 4,'7.jpg');
insert into book values(8, 'Head First HTML5 Programming', 570,7,'8.jpg');
insert into book values(9, 'Advanced Engineering Mathematics', 633,5,'9.jpg');
insert into book values(10, 'Electricity & Magnetism for JEE', 385, 1,'10.jpg');
insert into book values(11, 'Higher Engineering Mathematics', 594,6,'11.jpg');
insert into book values(12, 'Head First Java', 609,7,'12.jpg');
insert into book values(13, 'Data Structures Through C', 214,9,'13.jpg');
insert into book values(14, 'Head First Python', 425,7,'14.jpg');
insert into book values(15, 'Let Us C++', 240,9,'15.jpg');
insert into book values(16, 'Differential Geometry', 1200,10,'16.jpg');
insert into book values(17, 'Monuments Of India', 144,8,'17.jpg');

insert into book_author values(1, 8);
insert into book_author values(2, 10);
insert into book_author values(2, 3);
insert into book_author values(2, 6);
insert into book_author values(2, 11);
insert into book_author values(3, 1);
insert into book_author values(4, 13);
insert into book_author values(4, 9);
insert into book_author values(5, 12);
insert into book_author values(5, 1);
insert into book_author values(5, 6);
insert into book_author values(6, 1);
insert into book_author values(6, 8);
insert into book_author values(7, 14);
insert into book_author values(7, 11);
insert into book_author values(7, 12);
insert into book_author values(7, 13);
insert into book_author values(7, 10);
insert into book_author values(8, 3);
insert into book_author values(8, 5);
insert into book_author values(8, 1);
insert into book_author values(9, 3);
insert into book_author values(10, 8);
insert into book_author values(10, 2);
insert into book_author values(10, 14);
insert into book_author values(11, 4);
insert into book_author values(11, 15);
insert into book_author values(12, 15);
insert into book_author values(12, 14);
insert into book_author values(13, 12);
insert into book_author values(13, 10);
insert into book_author values(13, 4);
insert into book_author values(14, 1);
insert into book_author values(14, 8);
insert into book_author values(14, 14);
insert into book_author values(15, 9);
insert into book_author values(15, 6);
insert into book_author values(15, 10);
insert into book_author values(16, 15);
insert into book_author values(16, 13);
insert into book_author values(16, 4);
insert into book_author values(12, 18);
insert into book_author values(13, 16);
insert into book_author values(7, 17);
insert into book_author values(9, 19);
insert into book_author values(3, 20);

insert into store_book values(1, 10);
insert into store_book values(1, 12);
insert into store_book values(1, 9);
insert into store_book values(1, 2);
insert into store_book values(1, 5);
insert into store_book values(1, 7);
insert into store_book values(1, 1);
insert into store_book values(1, 3);
insert into store_book values(1, 15);
insert into store_book values(2, 3);
insert into store_book values(2, 1);
insert into store_book values(2, 6);
insert into store_book values(2, 2);
insert into store_book values(2, 7);
insert into store_book values(2, 4);
insert into store_book values(2, 12);
insert into store_book values(2, 15);
insert into store_book values(2, 11);
insert into store_book values(3, 1);
insert into store_book values(3, 3);
insert into store_book values(3, 6);
insert into store_book values(3, 9);
insert into store_book values(3, 4);
insert into store_book values(3, 12);
insert into store_book values(3, 13);
insert into store_book values(3, 14);
insert into store_book values(4, 14);
insert into store_book values(4, 11);
insert into store_book values(4, 12);
insert into store_book values(4, 9);
insert into store_book values(4, 3);
insert into store_book values(4, 10);
insert into store_book values(4, 4);
insert into store_book values(4, 1);
insert into store_book values(5, 1);
insert into store_book values(5, 2);
insert into store_book values(5, 6);
insert into store_book values(5, 3);
insert into store_book values(5, 8);
insert into store_book values(5, 12);
insert into store_book values(5, 15);
insert into store_book values(5, 4);
insert into store_book values(5, 7);
insert into store_book values(6, 7);
insert into store_book values(6, 1);
insert into store_book values(6, 5);
insert into store_book values(6, 2);
insert into store_book values(6, 12);
insert into store_book values(7, 7);
insert into store_book values(7, 1);
insert into store_book values(7, 8);
insert into store_book values(7, 3);
insert into store_book values(7, 14);
insert into store_book values(7, 12);
insert into store_book values(7, 11);
insert into store_book values(8, 12);
insert into store_book values(8, 1);
insert into store_book values(8, 7);
insert into store_book values(8, 9);
insert into store_book values(8, 10);
insert into store_book values(8, 17);
insert into store_book values(8, 15);
insert into store_book values(9, 4);
insert into store_book values(9, 12);
insert into store_book values(9, 13);
insert into store_book values(9, 14);
insert into store_book values(9, 11);
insert into store_book values(9, 17);
insert into store_book values(10, 7);
insert into store_book values(10, 1);
insert into store_book values(10, 3);
insert into store_book values(10, 15);
insert into store_book values(10, 3);
insert into store_book values(10, 6);
insert into store_book values(10, 2);